Bump WordPress deploy to php 8

diff --git a/blog/Dockerfile b/blog/Dockerfile
--- a/blog/Dockerfile
+++ b/blog/Dockerfile
@@ -2,22 +2,73 @@ FROM php:8.0-fpm
 
 WORKDIR /blog
 
-RUN set -ex \
-  && apt-get update && apt-get install -y \
-  # WordPress requirements
-  libmagickwand-dev zlib1g-dev libzip-dev --no-install-recommends \
-  \ 
-  && docker-php-ext-install mysqli && docker-php-ext-enable mysqli \
-  && docker-php-ext-install exif zip gd \
-  \
-  && pecl install imagick \ 
-  && docker-php-ext-enable imagick \
-  \
-  # Clear cache
-  && apt-get clean && rm -rf /var/lib/apt/lists/* \
-  \
-  # Add user to run the php application
-  && groupadd -g 1000 mancelot \
+RUN set -ex; \
+    \
+    savedAptMark="$(apt-mark showmanual)"; \
+    \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+        libfreetype6-dev \
+        libjpeg-dev \
+        libpng-dev \
+        libzip-dev \
+    ; \
+    \
+    docker-php-ext-configure gd \
+        --with-freetype \
+        --with-jpeg \
+    ; \
+    docker-php-ext-install -j "$(nproc)" \
+        bcmath \
+        exif \
+        gd \
+        mysqli \
+        zip \
+    ; \
+    \
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+    apt-mark auto '.*' > /dev/null; \
+    apt-mark manual $savedAptMark; \
+    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+        | awk '/=>/ { print $3 }' \
+        | sort -u \
+        | xargs -r dpkg-query -S \
+        | cut -d: -f1 \
+        | sort -u \
+        | xargs -rt apt-mark manual; \
+    \
+    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+    rm -rf /var/lib/apt/lists/*
+
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+    docker-php-ext-enable opcache; \
+    { \
+        echo 'opcache.memory_consumption=128'; \
+        echo 'opcache.interned_strings_buffer=8'; \
+        echo 'opcache.max_accelerated_files=4000'; \
+        echo 'opcache.revalidate_freq=2'; \
+        echo 'opcache.fast_shutdown=1'; \
+    } > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+# https://www.php.net/manual/en/errorfunc.constants.php
+# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+        echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+        echo 'display_errors = Off'; \
+        echo 'display_startup_errors = Off'; \
+        echo 'log_errors = On'; \
+        echo 'error_log = /dev/stderr'; \
+        echo 'log_errors_max_len = 1024'; \
+        echo 'ignore_repeated_errors = On'; \
+        echo 'ignore_repeated_source = Off'; \
+        echo 'html_errors = Off'; \
+    } > /usr/local/etc/php/conf.d/error-logging.ini
+
+
+# Add user to run the php application
+RUN groupadd -g 1000 mancelot \
   && useradd -u 1000 -ms /bin/bash -g mancelot mancelot
 
 # Copy application directory contents
